source: 
  - https://raw.githubusercontent.com/naiba/nezha/master/script/install.sh

features:
  python: true
  
nginx:
  locations:
    /:
      proxy_pass: http://127.0.0.1:8080
      proxy_set_header: 
        Host: $host
        X-Real-IP: $remote_addr

commands:
  - curl -L https://raw.githubusercontent.com/naiba/nezha/master/script/install.sh -o agent.sh
  - chmod +x agent.sh
  - ./agent.sh install
  - python3 server.py &
